INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (1, 'ALPINE', 'Filter', '25/200', 38.92, 311.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (2, 'ALPINE', 'Original', '25/200', 38.92, 311.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (3, 'ALPINE', 'Rich', '25/200', 38.92, 311.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (4, 'ALPINE', 'Fine', '25/200', 38.92, 311.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (5, 'ALPINE', 'Supreme', '25/200', 38.92, 311.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (6, 'BOND STREET CLASSIC', 'Blue', '20/200', 23.19, 230.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (7, 'BOND STREET CLASSIC', 'Gold', '20/200', 23.19, 230.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (8, 'BOND STREET', 'Red', '20/200', 25.89, 258.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (9, 'BOND STREET', 'Blue', '20/200', 25.89, 258.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (10, 'BOND STREET', 'Gold', '20/200', 25.89, 258.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (11, 'BOND STREET', 'Red', '25/200', 31.53, 251.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (12, 'BOND STREET', 'Blue', '25/200', 31.53, 251.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (13, 'BOND STREET', 'Gold', '25/200', 31.53, 251.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (14, 'BOND STREET', 'Red', '30/180', 36.22, 216.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (15, 'BOND STREET', 'Blue', '30/180', 36.22, 216.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (16, 'BOND STREET', 'Gold', '30/180', 36.22, 216.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (17, 'BOND STREET', 'Red', '40/160', 49.18, 195.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (18, 'BOND STREET', 'Blue', '40/160', 49.18, 195.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (19, 'BOND STREET', 'Gold', '40/160', 49.18, 195.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (20, 'BOND STREET', 'Menthol', '40/160', 49.18, 195.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (21, 'CHOICE Signature', 'Bold', '20/200', 21.63, 215.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (22, 'CHOICE Signature', 'Classic', '20/200', 21.63, 215.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (23, 'CHOICE Signature', 'Blonde', '20/200', 21.63, 215.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (24, 'CHOICE Signature', 'Bold', '25/200', 28.74, 228.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (25, 'CHOICE Signature', 'Classic', '25/200', 28.74, 228.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (26, 'CHOICE Signature', 'Red', '40/160', 46.40, 184.60, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (27, 'CHOICE Signature', 'Blue', '40/160', 46.40, 184.60, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (28, 'CHOICE Signature', 'Gold', '40/160', 46.40, 184.60, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (29, 'HARMONY', 'Blue', '20/200', 23.08, 230.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (30, 'HARMONY', 'Gold', '20/200', 23.08, 230.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (31, 'LONGBEACH', 'Yellow', '20/200', 25.88, 257.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (32, 'LONGBEACH', 'Blue', '20/200', 25.88, 257.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (33, 'LONGBEACH', 'Silver', '20/200', 25.88, 257.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (34, 'LONGBEACH', 'Menthol', '20/200', 25.88, 257.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (35, 'LONGBEACH', 'Yellow', '25/200', 21.98, 218.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (36, 'LONGBEACH', 'Blue', '25/200', 21.98, 218.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (37, 'LONGBEACH', 'Silver', '25/200', 21.98, 218.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (38, 'LONGBEACH', 'Menthol', '25/200', 21.98, 218.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (39, 'LONGBEACH', 'Yellow', '30/180', 41.42, 248.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (40, 'LONGBEACH', 'Blue', '30/180', 41.42, 248.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (41, 'LONGBEACH', 'Silver', '30/180', 41.42, 248.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (42, 'LONGBEACH', 'Menthol', '30/180', 41.42, 248.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (43, 'LONGBEACH  Moments', 'West', '30/180', 38.69, 232.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (44, 'LONGBEACH  Moments', 'North', '30/180', 38.69, 232.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (45, 'LONGBEACH  Moments', 'East', '30/180', 38.69, 232.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (46, 'LONGBEACH  Moments', 'Menthol', '30/180', 38.69, 232.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (47, 'LONGBEACH ', 'Yellow', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (48, 'LONGBEACH ', 'Blue', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (49, 'LONGBEACH ', 'Silver', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (50, 'LONGBEACH ', 'White', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (51, 'LONGBEACH ', 'Menthol', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (52, 'LONGBEACH ', 'Menthol Fresh', '40/160', 51.13, 203.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (53, 'MARLBORO', 'Red', '20/200', 30.15, 301.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (54, 'MARLBORO', 'Gold', '20/200', 30.15, 301.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (55, 'MARLBORO', 'Ice', '20/200', 30.15, 301.40, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (56, 'MARLBORO', 'Red', '25/200', 37.51, 300.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (57, 'MARLBORO', 'Blue', '25/200', 37.51, 300.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (58, 'MARLBORO', 'Gold', '25/200', 37.51, 300.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (59, 'MARLBORO', 'Ice', '25/200', 37.51, 300.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (60, 'MARLBORO', 'Menthol', '25/200', 37.51, 300.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (61, 'PETER JACKSON', 'Blue', '20/200', 28.71, 286.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (62, 'PETER JACKSON', 'Gold', '20/200', 28.71, 286.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (63, 'PETER JACKSON', 'Silver', '20/201', 28.71, 286.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (64, 'PETER JACKSON', 'Blue', '25/200', 32.57, 260.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (65, 'PETER JACKSON', 'Gold', '25/200', 32.57, 260.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (66, 'PETER JACKSON', 'Red', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (67, 'PETER JACKSON', 'Blue', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (68, 'PETER JACKSON', 'Gold', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (69, 'PETER JACKSON', 'Silver', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (70, 'PETER JACKSON', 'White', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (71, 'PETER JACKSON', 'Menthol', '30/180', 41.80, 249.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (72, 'PETER JACKSON CLASSIC', 'Blue', '30/180', 40.15, 240.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (73, 'PETER JACKSON CLASSIC', 'Gold', '30/180', 40.15, 240.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (74, 'PETER JACKSON', 'Blue', '40/160', 51.08, 203.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (75, 'PETER JACKSON', 'Gold', '40/160', 51.08, 203.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (76, 'BOND STREET RYO', 'Red', '15/75G', 24.20, 120.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (77, 'BOND STREET RYO', 'Blue', '15/75G', 24.20, 120.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (78, 'BOND STREET RYO', 'Gold', '15/75G', 24.20, 120.00, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (79, 'CHOICE RYO', 'Red', '25/125G', 39.44, 197.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (80, 'CHOICE RYO', 'Blue', '25/125G', 39.44, 197.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (81, 'CHOICE RYO', 'Gold', '25/125G', 39.44, 197.20, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (82, 'CRAFTSMAN RYO', 'Expresso', '15/75G', 25.49, 127.45, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (83, 'CRAFTSMAN RYO', 'Brunswick', '15/75G', 25.49, 127.45, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (84, 'CRAFTSMAN RYO', 'Rum', '15/75G', 25.49, 127.45, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (85, 'CRAFTSMAN RYO', 'Brunswick', '25/125G', 39.48, 197.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (86, 'CRAFTSMAN RYO', 'Rum', '25/125G', 39.48, 197.30, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (87, 'LONGBEACH RYO', 'Rich', '25G/250G', 37.96, 188.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (88, 'LONGBEACH RYO', 'Yellow', '25G/250G', 37.96, 188.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (89, 'LONGBEACH RYO', 'Rich', '45G/225G', 69.36, 345.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (90, 'LONGBEACH RYO', 'Yellow', '45G/225G', 69.36, 345.80, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (91, 'PETER JACKSON RYO', 'Blue', '15G/75G', 25.18, 124.90, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (92, 'PETER JACKSON RYO', 'Blue', '25G/125G', 39.50, 196.50, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (93, 'WEE WILLEM', 'Blue', '10S/100', 21.78, 217.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (94, 'WEE WILLEM', 'Regular', '10S/100', 21.78, 217.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (95, 'WEE WILLEM', 'Gold', '10S/100', 21.78, 217.70, 'PML');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (96, 'BENSON HEDGES', 'Classic', '20/200', 29.16, 291.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (97, 'BENSON HEDGES', 'Smooth', '20/200', 29.16, 291.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (98, 'BENSON HEDGES', 'Classic', '25/200', 39.35, 314.75, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (99, 'BENSON HEDGES', 'Smooth', '25/200', 39.35, 314.75, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (100, 'BENSON HEDGES', 'Fine', '25/200', 39.35, 314.75, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (101, 'BENSON HEDGES', 'Ultimate', '25/200', 39.35, 314.75, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (102, 'BENSON HEDGES', 'Classic', '30/180', 44.40, 266.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (103, 'BENSON HEDGES', 'Smooth', '30/180', 44.40, 266.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (104, 'DUNHILL ORIGIONAL', 'Red', '20/200', 29.16, 291.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (105, 'DUNHILL ORIGIONAL', 'Blue', '20/200', 29.16, 291.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (106, 'DUNHILL ORIGIONAL', 'Silver', '20/200', 29.16, 291.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (107, 'DUNHILL FINE CUT', 'Navy', '20/200', 33.34, 333.35, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (108, 'DUNHILL FINE CUT', 'White', '20/200', 33.34, 333.35, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (109, 'DUNHILL', 'Red', '23/184', 36.07, 288.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (110, 'DUNHILL', 'Blue', '23/184', 36.07, 288.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (111, 'DUNHILL', 'White', '23/184', 36.07, 288.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (112, 'DUNHILL ORIGIONAL', 'Blue', '25/200', 34.72, 277.75, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (113, 'HOLIDAY KINGS', 'Red', '22/176', 26.81, 214.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (114, 'HOLIDAY KINGS', 'Blue', '22/176', 26.81, 214.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (115, 'HOLIDAY KINGS', 'Gold', '22/176', 26.81, 214.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (116, 'HOLIDAY KINGS', 'Menthol', '22/176', 26.81, 214.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (117, 'HOLIDAY KINGS', 'Red', '50/200', 66.29, 265.15, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (118, 'HOLIDAY KINGS', 'Blue', '50/200', 66.29, 265.15, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (119, 'HOLIDAY KINGS', 'Gold', '50/200', 66.29, 265.15, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (120, 'PALL MALL ', 'Red', '20/200', 22.08, 217.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (121, 'PALL MALL ', 'Blue', '20/200', 22.08, 217.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (122, 'PALL MALL ', 'Amber', '20/200', 22.08, 217.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (123, 'PALL MALL ', 'Red', '30/180', 36.35, 218.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (124, 'PALL MALL ', 'Blue', '30/180', 36.35, 218.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (125, 'PALL MALL ', 'Amber', '30/180', 36.35, 218.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (126, 'PALL MALL ', 'Red', '40/120', 41.83, 124.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (127, 'PALL MALL ', 'Blue', '40/120', 41.83, 124.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (128, 'PALL MALL SLIMS', 'Menthol', '23/138', 35.65, 213.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (129, 'ROTHMANS COOL CRUSH', 'Red', '20/200', 25.93, 259.25, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (130, 'ROTHMANS COOL CRUSH', 'Blue', '20/200', 25.93, 259.25, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (131, 'ROTHMANS COOL CRUSH', 'Gold', '20/200', 25.93, 259.25, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (132, 'ROTHMANS COOL CRUSH', 'Red', '25/200', 27.60, 219.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (133, 'ROTHMANS COOL CRUSH', 'Blue', '25/200', 27.60, 219.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (134, 'ROTHMANS COOL CRUSH', 'Gold', '25/200', 27.60, 219.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (135, 'ROTHMANS SUPERKINGS', 'Red', '20/200', 27.54, 275.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (136, 'ROTHMANS SUPERKINGS', 'Blue', '20/200', 27.54, 275.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (137, 'ROTHMANS SUPERKINGS', 'Menthol', '20/200', 27.54, 275.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (138, 'ROTHMANS', 'Red', '25/200', 32.87, 262.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (139, 'ROTHMANS', 'Blue', '25/200', 32.87, 262.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (140, 'ROTHMANS', 'Gold', '25/200', 32.87, 262.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (141, 'ROTHMANS', 'Silver', '25/200', 32.87, 262.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (142, 'ROTHMANS', 'Menthol', '25/200', 32.87, 262.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (143, 'ROTHMANS', 'Red', '30/180', 37.12, 222.65, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (144, 'ROTHMANS', 'Blue', '30/180', 37.12, 222.65, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (145, 'ROTHMANS', 'Gold', '30/180', 37.12, 222.65, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (146, 'ROTHMANS', 'Red', '40/120', 49.10, 149.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (147, 'ROTHMANS', 'Blue', '40/120', 49.10, 149.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (148, 'ROTHMANS', 'Gold', '40/120', 49.10, 149.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (149, 'ROTHMANS', 'Silver', '40/120', 49.10, 149.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (150, 'ROTHMANS', 'Menthol', '40/120', 49.10, 149.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (151, 'ROTHMANS', 'Black', '40/200', 49.10, 244.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (152, 'ROTHMANS', 'Red', '50/200', 65.74, 262.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (153, 'ROTHMANS', 'Blue', '50/200', 65.74, 262.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (154, 'ROTHMANS', 'Gold', '50/200', 65.74, 262.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (155, 'VOGUE S/SLIMS', 'Blue', '20/200', 36.30, 362.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (156, 'VOGUE S/SLIMS', 'Menthol', '20/200', 36.30, 362.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (157, 'WINFIELD FLOW FILTER', 'Blue', '20/200', 30.23, 302.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (158, 'WINFIELD FLOW FILTER', 'Gold', '20/200', 30.23, 302.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (159, 'WINFIELD FLOW FILTER', 'Red', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (160, 'WINFIELD FLOW FILTER', 'Blue', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (161, 'WINFIELD FLOW FILTER', 'Gold', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (162, 'WINFIELD FLOW FILTER', 'Sky Blue', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (163, 'WINFIELD FLOW FILTER', 'Grey', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (164, 'WINFIELD FLOW FILTER', 'White', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (165, 'WINFIELD FLOW FILTER', 'Menthol Fresh', '25/200', 37.50, 299.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (166, 'WINFIELD  JETS', 'Blue', '23/138', 32.64, 195.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (167, 'WINFIELD  JETS', 'Gold', '23/138', 32.64, 195.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (168, 'WINFIELD MAX', 'Blue', '32/128', 37.40, 148.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (169, 'WINFIELD MAX', 'Gold', '32/128', 37.40, 148.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (170, 'WINFIELD ORIGIONAL', 'Red', '20/200', 27.31, 273.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (171, 'WINFIELD ORIGIONAL', 'Blue', '20/200', 27.31, 273.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (172, 'WINFIELD ORIGIONAL', 'Gold', '20/200', 27.31, 273.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (173, 'WINFIELD ORIGIONAL', 'Red', '25/200', 31.85, 253.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (174, 'WINFIELD ORIGIONAL', 'Blue', '25/200', 31.85, 253.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (175, 'WINFIELD ORIGIONAL', 'Gold', '25/200', 31.85, 253.80, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (176, 'WINFIELD', 'Red', '30/180', 42.22, 253.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (177, 'WINFIELD', 'Blue', '30/180', 42.22, 253.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (178, 'WINFIELD', 'Gold', '30/180', 42.22, 253.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (179, 'WINFIELD', 'Sky Blue', '30/180', 42.22, 253.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (180, 'WINFIELD', 'Grey', '30/180', 42.22, 253.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (181, 'WINFIELD', 'Blue', '40/120', 53.24, 159.70, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (182, 'WINFIELD', 'Gold', '40/120', 53.24, 159.70, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (183, 'WINFIELD', 'Menthol Fresh', '40/120', 53.24, 159.70, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (184, 'WINFIELD OPTIMUM ', 'Crush Blue', '20/200', 28.75, 287.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (185, 'WINFIELD OPTIMUM ', 'Crush Sky Blue', '20/200', 28.75, 287.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (186, 'WINFIELD OPTIMUM ', 'Crush Blue', '25/200', 34.12, 272.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (187, 'WINFIELD OPTIMUM ', 'Crush Gold', '25/200', 34.12, 272.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (188, 'WINFIELD OPTIMUM ', 'Crush Sky Blue', '25/200', 34.12, 272.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (189, 'WINFIELD OPTIMUM ', 'Crush Menthol Boost', '25/200', 34.12, 272.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (190, 'WINFIELD OPTIMUM ', 'Crush Blue', '30/180', 40.74, 244.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (191, 'WINFIELD OPTIMUM ', 'Crush Gold', '30/180', 40.74, 244.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (192, 'WINFIELD OPTIMUM ', 'Crush Sky Blue', '30/180', 40.74, 244.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (193, 'WINFIELD OPTIMUM ', 'Crush Blue', '40/120', 50.53, 150.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (194, 'WINFIELD OPTIMUM ', 'Crush Gold', '40/120', 50.53, 150.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (195, 'CAPSTAN', 'Makers Blend', '15G/75G', 21.74, 107.70, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (196, 'CAPSTAN', 'Makers Blend', '25G/125G', 36.30, 180.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (197, 'HOLIDAY', 'Bright Blue', '25G/125G', 39.09, 195.40, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (198, 'HOLIDAY', 'Bright Blue', '50G/250G', 84.33, 421.65, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (199, 'PORT ROYAL RAW', 'Raw', '15G /75G', 25.00, 125.00, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (200, 'PORT ROYAL RAW', 'Raw', '25G/125G', 42.59, 212.90, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (201, 'PORT ROYAL RR', 'Original Rum & Wine', '15G /75G', 25.37, 126.85, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (202, 'PORT ROYAL RR', 'Highland Whisky', '15G /75G', 25.37, 126.85, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (203, 'PORT ROYAL RR', 'Original Rum & Wine', '25G/125G', 44.87, 224.35, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (204, 'PORT ROYAL RR', 'Original Rum & Wine', '40G/200G', 72.59, 362.95, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (205, 'PORT ROYAL RR', 'Original Rum & Wine', '50G/250G', 90.50, 452.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (206, 'ROTHMANS RYO', 'Red ', '20G/100G', 32.27, 161.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (207, 'ROTHMANS RYO', 'Blue', '20G/100G', 32.27, 161.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (208, 'ROTHMANS RYO', 'Gold', '20G/100G', 32.27, 161.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (209, 'WINFIELD TOBACCO', 'Red ', '20G/100G', 35.41, 177.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (210, 'WINFIELD TOBACCO', 'Blue', '20G/100G', 35.41, 177.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (211, 'WINFIELD TOBACCO', 'Gold', '20G/100G', 35.41, 177.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (212, 'WINFIELD TOBACCO', 'Spiced Rum', '20G/100G', 35.41, 177.05, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (213, 'WINFIELD TOBACCO', 'Red', '40G/200G', 69.86, 349.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (214, 'WINFIELD TOBACCO', 'Blue', '40G/200G', 69.86, 349.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (215, 'WINFIELD TOBACCO', 'Gold', '40G/200G', 69.86, 349.30, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (216, 'WINFIELD TOBACCO', 'Red ', '50G/250G', 87.82, 439.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (217, 'WINFIELD TOBACCO', 'Blue', '50G/250G', 87.82, 439.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (218, 'WINFIELD TOBACCO', 'Gold', '50G/250G', 87.82, 439.10, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (219, 'WINFIELD OPTIMUM TOBACCO', 'Blue', '25G/125G', 36.10, 179.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (220, 'WINFIELD OPTIMUM TOBACCO', 'Gold', '25G/125G', 36.10, 179.50, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (221, 'CAPTAIN BLACK', 'Classic', '20/200', 34.36, 343.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (222, 'CAPTAIN BLACK', 'Dark', '20/200', 34.36, 343.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (223, 'CAPTAIN BLACK', 'Cherise', '20/200', 34.36, 343.60, 'BATA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (224, 'CAMEL', 'Filter, Blue', '25/200', 37.06, 295.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (225, 'DAVIDOFF', 'Classic, Gold', '20/200', 32.63, 326.20, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (226, 'ESCORT', 'Red, Blue', '21/210', 28.59, 285.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (227, 'HORIZON 93MM', 'Red', '20/200', 24.95, 248.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (228, 'HORIZON 93MM', 'Purple', '20/200', 24.95, 248.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (229, 'HORIZON 93MM', 'Blue', '20/200', 24.95, 248.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (230, 'HORIZON 93MM', 'Gold', '20/200', 24.95, 248.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (231, 'HORIZON', 'Red', '30/180', 36.43, 217.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (232, 'HORIZON', 'Purple', '30/180', 36.43, 217.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (233, 'HORIZON', 'Blue', '30/180', 36.43, 217.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (234, 'HORIZON', 'Orange', '30/180', 36.43, 217.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (235, 'HORIZON', 'White', '30/180', 36.43, 217.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (236, 'HORIZON', 'Red', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (237, 'HORIZON', 'Purple', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (238, 'HORIZON', 'Blue', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (239, 'HORIZON', 'Orange', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (240, 'HORIZON', 'Yellow', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (241, 'HORIZON', 'White', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (242, 'HORIZON', 'Menthol Blue', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (243, 'HORIZON', 'Menthol Yellow', '50/200', 64.82, 259.25, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (244, 'JPS SUPERKINGS', 'Red', '20/200', 26.85, 267.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (245, 'JPS SUPERKINGS', 'Blue', '20/200', 26.85, 267.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (246, 'JPS SUPERKINGS', 'Gold', '20/200', 26.85, 267.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (247, 'JPS SUPERKINGS', 'Silver', '20/200', 26.85, 267.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (248, 'JPS SUPERKINGS', 'Menthol', '20/200', 26.85, 267.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (249, 'JPS', 'Red', '20/200', 25.75, 256.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (250, 'JPS', 'Blue', '20/200', 25.75, 256.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (251, 'JPS', 'Gold', '20/200', 25.75, 256.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (252, 'JPS', 'Red', '25/200', 31.11, 247.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (253, 'JPS', 'Blue', '25/200', 31.11, 247.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (254, 'JPS', 'Gold', '25/200', 31.11, 247.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (255, 'JPS', 'Silver', '25/200', 31.11, 247.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (256, 'JPS', 'Menthol', '25/200', 31.11, 247.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (257, 'JPS', 'Red', '30/180', 36.00, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (258, 'JPS', 'Blue', '30/180', 36.00, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (259, 'JPS', 'Gold', '30/180', 36.00, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (260, 'JPS', 'Red', '40/160', 50.73, 201.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (261, 'JPS', 'Blue', '40/160', 50.73, 201.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (262, 'JPS', 'Gold', '40/160', 50.73, 201.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (263, 'JPS', 'Silver', '40/160', 50.73, 201.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (264, 'JPS', 'Menthol', '40/160', 50.73, 201.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (265, 'JPS+ Crushball', 'Red', '20/200', 21.39, 212.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (266, 'JPS+ Crushball', 'Blue', '20/200', 21.39, 212.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (267, 'JPS+ Crushball', 'Gold', '20/200', 21.39, 212.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (268, 'JPS+ Crushball', 'Red', '25/200', 28.94, 230.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (269, 'JPS+ Crushball', 'Blue', '25/200', 28.94, 230.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (270, 'JPS+ Crushball', 'Gold', '25/200', 28.94, 230.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (271, 'PARKER & SIMPSON', 'Red', '20/200', 21.59, 214.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (272, 'PARKER & SIMPSON', 'Blue', '20/200', 21.59, 214.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (273, 'PARKER & SIMPSON', 'Gold', '20/200', 21.59, 214.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (274, 'PARKER & SIMPSON', 'Red', '25/200', 26.85, 213.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (275, 'PARKER & SIMPSON', 'Blue', '25/200', 26.85, 213.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (276, 'PARKER & SIMPSON', 'Gold', '25/200', 26.85, 213.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (277, 'PARKER & SIMPSON', 'Red', '30/180', 35.25, 210.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (278, 'PARKER & SIMPSON', 'Blue', '30/180', 35.25, 210.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (279, 'PARKER & SIMPSON', 'Gold', '30/180', 35.25, 210.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (280, 'PARKER & SIMPSON', 'Red', '40/160', 41.15, 163.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (281, 'PARKER & SIMPSON', 'Blue', '40/160', 41.15, 163.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (282, 'PARKER & SIMPSON', 'Gold', '40/160', 41.15, 163.60, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (283, 'PETER STUYVESANT', 'Filter Red', '20/200', 30.09, 299.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (284, 'PETER STUYVESANT', 'Classic Blue', '20/200', 30.09, 299.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (285, 'PETER STUYVESANT EDGE CRUSHBALL', 'Red', '20/200', 27.15, 270.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (286, 'PETER STUYVESANT EDGE CRUSHBALL', 'Blue', '20/200', 27.15, 270.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (287, 'PETER STUYVESANT', 'Filter Red', '25/200', 37.25, 297.95, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (288, 'PETER STUYVESANT', 'Classic Blue', '25/200', 37.25, 297.95, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (289, 'PETER STUYVESANT', 'Filter Red', '30/180', 41.97, 250.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (290, 'PETER STUYVESANT', 'Classic Blue', '30/180', 41.97, 250.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (291, 'BANK', 'Aromatic', '50G/250G', 93.58, 467.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (292, 'CHAMPION', 'Ruby', '15G/75G', 27.15, 134.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (293, 'CHAMPION', 'Ruby', '20G/100G', 35.37, 176.85, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (294, 'CHAMPION', 'Ruby', '25G/125G', 43.01, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (295, 'CHAMPION', 'Blue', '25G/125G', 43.01, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (296, 'CHAMPION', 'Red', '25G/125G', 43.01, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (297, 'CHAMPION ROUND MIDNIGHT', 'Rum', '25G/125G', 43.01, 215.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (298, 'CHAMPION', 'Ruby', '50G/250G', 86.58, 432.85, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (299, 'CHAMPION', 'Blue', '50G/250G', 86.58, 432.85, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (300, 'CHAMPION', 'Red', '50G/250G', 86.58, 432.85, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (301, 'CHAMPION', 'Ruby', '40G/200G', 68.69, 343.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (302, 'CHAMPION ROUND MIDNIGHT', 'Rum', '40G/200G', 68.69, 343.00, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (303, 'DR PAT', 'Distinctive', '50G/250G', 93.58, 467.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (304, 'DRUM', 'Classic Blue', '30G/300G', 53.59, 535.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (305, 'DRUM', 'Rich Sky', '30G/300G', 53.59, 535.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (306, 'DRUM', 'Smooth Yellow', '30G/300G', 53.59, 535.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (307, 'DRUM', 'Classic Blue', '50G/500G', 88.81, 888.05, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (308, 'DRUM', 'Rich Sky', '50G/500G', 88.81, 888.05, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (309, 'DRUM', 'Smooth Yellow', '50G/500G', 88.81, 888.05, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (310, 'DRUM', 'Menthol', '50G/500G', 88.81, 888.05, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (311, 'GOLDEN VIRGINIA', '-', '30G/300G', 56.05, 560.45, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (312, 'HORIZON RYO', 'Blue', '25G/125G', 39.10, 194.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (313, 'HORIZON RYO', 'Menthol', '25G/125G', 39.10, 194.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (314, 'HORIZON RYO', 'Blue', '50G/250G', 77.56, 386.80, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (315, 'JPS RYO', 'Red', '25G/125G', 37.79, 376.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (316, 'JPS RYO', 'Blue', '25G/125G', 37.79, 376.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (317, 'JPS RYO', 'Gold', '25G/125G', 37.79, 376.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (318, 'JPS RYO SELECT', 'Hand Stripped Blend', '20G/100G', 32.07, 160.35, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (319, 'JPS RYO SELECT', 'Hand Stripped Blend', '40G/200G', 61.90, 309.45, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (320, 'PARKER & SIMPSON TOBACCO', 'Blue', '15G/75G', 21.70, 107.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (321, 'PETER STUYVESANT TOB', 'Classic Blue', '30G/300G', 56.40, 281.95, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (322, 'RIVERSTONE', 'Premium Rum Blend', '15/75G', 21.70, 107.50, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (323, 'RIVERSTONE', 'Premium Rum Blend', '20/100G', 31.86, 158.30, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (324, 'RIVERSTONE', 'Premium Rum Blend', '25/150G', 35.39, 175.95, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (325, 'STOCKMANS', '-', '50G/250G', 88.19, 440.90, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (326, 'WHITE OX', '-', '25G/125G', 44.03, 220.15, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (327, 'WHITE OX', '-', '50G/500G', 87.38, 873.75, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (328, 'AMPHORA', 'Pipe Tobacco', '50G/250G', 94.96, 474.75, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (329, 'DR PAT (PIPE)', 'Pipe Tobacco', '50G/250G', 94.28, 471.35, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (330, 'LOG CABIN', 'Pipe Tobacco', '50G/250G', 94.43, 472.15, 'ITA');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (331, 'TS', 'Red', '20/200', 21.10, 210.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (332, 'TS', 'Blue', '20/200', 21.10, 210.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (333, 'TS', 'Gold', '20/200', 21.10, 210.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (334, 'Reef', 'Red', '20/200', 22.08, 219.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (335, 'Reef', 'Blue', '20/200', 22.08, 219.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (336, 'Reef', 'Gold', '20/200', 22.08, 219.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (337, 'Reef', 'Menthol', '20/200', 22.08, 219.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (338, 'Reef', 'Red', '25/200', 28.00, 223.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (339, 'Reef', 'Blue', '25/200', 28.00, 223.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (340, 'Reef', 'Gold', '25/200', 28.00, 223.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (341, 'Tycoon', 'Cigar', '2/20', 3.01, 30.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (342, 'Tycoon', 'Cigar', '20/200', 26.58, 264.77, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (343, 'Manitou', 'Organic', '20/200', 29.20, 291.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (344, 'Manitou RYO 30G', 'Organic', '30G/150G', 55.20, 275.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (345, 'Amanda', '-', '10S/50S', 30.16, 150.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (346, 'Cafe Creme ', 'Original', '10S/100S', 20.11, 201.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (347, 'Cafe Creme ', 'Blue', '10S/100S', 20.11, 201.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (348, 'Cafe Creme ', 'Aroma', '10S/100S', 20.11, 201.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (349, 'Cafe Creme Filter', 'Aroma', '10S/100S', 21.21, 212.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (350, 'Cafe Creme Filter', 'Vanila', '10S/100S', 18.94, 189.40, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (351, 'Henri Wintermans', 'Half Corona', '5S/25S', 37.42, 187.10, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (352, 'Henri Wintermans', 'Longs', '5S/25S', 33.46, 167.30, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (353, 'Henri Wintermans', 'Shorts', '5S/25S', 23.89, 119.45, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (354, 'Colts', 'Rum', '20/200', 29.68, 296.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (355, 'Colts', 'Vanila', '20/200', 29.68, 296.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (356, 'Colts', 'Cherry', '20/200', 29.68, 296.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (357, 'Borkum Riff ', 'Cherry Cavendish', '30g/150g', 57.60, 288.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (358, 'Tally-Ho Slim 120 Filters 7mm', 'Filter', '10/Box', 0.89, 8.91, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (359, 'Tally-Ho Ultra Slim 150 Filters 6mm', 'Filter', '10/Box', 0.89, 8.91, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (360, 'Tally-Ho Micro Slim 120 Filters 5.6mm', 'Filter', '10/Box', 0.89, 17.82, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (361, 'VENTTI FILTER', 'Red (Original)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (362, 'VENTTI FILTER', 'Yelow (Slim)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (363, 'VENTTI FILTER', 'Blue (Super Slim)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (364, 'VENTTI FILTER', 'Orange (Micro Slim)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (365, 'VENTTI FILTER', 'Green (Menthol)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (366, 'VENTTI FILTER', 'White (Extra Long Micro Slim)', '16/Box', 1.21, 16.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (367, 'Tally-Ho 50S Single', 'Paper', '100/Box', 0.64, 64.13, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (368, 'Tally-Ho 50S 5Pk', 'Paper', '50/Box', 3.00, 149.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (369, 'Tally-Ho Natura Regular ', 'Paper', '50/Box', 0.64, 32.07, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (370, 'Tally-Ho Natura king size slim', 'Paper', '50/Box', 0.96, 47.96, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (371, 'Rizla Singles Green 50S', 'Paper', '100/Box', 0.18, 8.80, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (372, 'Papers Papers 60', 'Paper', '50/Box', 1.60, 40.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (373, 'Rizla 100S', 'Paper', '100/Box', 0.38, 19.20, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (374, 'Rizla 32S', 'Paper', '50/Box', 0.86, 21.40, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (375, 'Ventti Paper', 'Paper', '100/Box', 0.46, 44.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (376, 'Ventti Paper 5Pack', 'Paper', '18/Box', 1.90, 28.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (377, 'Rollies Papers', 'Paper', '100/Box', 0.22, 22.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (378, 'Zig Zag Kingsize Red  32''S', 'Paper', '50/Box', 0.86, 43.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (379, 'Tally-Ho 100 Cigarette Tubes', 'Tubes', '5/Carton', 1.61, 8.03, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (380, 'Tally-Ho  Cigarette Maker', 'Cigarette maker', 'Cigarette maker', 6.35, 31.74, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (381, 'Vetti Tubes', 'Tubes', 'Tubes', 1.80, 9.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (382, 'Bic J25 Mini Lighter', 'Lighter', '50/Tray', 0.95, 35.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (383, 'Bic J26 Maxi Lighter', 'Lighter', '50/Tray', 1.06, 44.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (384, 'Gil  ', 'Lighter', '50/Tray', 0.30, 12.00, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (385, 'Zippo', 'Gas', '125ML', 3.50, 3.50, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (386, 'Ventti Fluid', 'Gas', '133ML', 3.50, 3.50, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (387, 'Ventti Gas', 'Gas', '300ML', 3.95, 23.70, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (388, 'Newport Gas ', 'Gas', '300ML', 3.50, 3.50, 'ZZZ');
INSERT INTO ausio.cigarette (Cig_id, Cig_brand, Cig_flavor, Cig_size, Cig_packet_price, Cig_carton_price, Cig_company) VALUES (389, 'Redhead Matches', 'Matches', '10/Box', 1.80, 1.80, 'ZZZ');